# Generated by Django 5.1.15 on 2026-05-22 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='e.g., page_view, course_view, search, enquiry_submit', max_length=50)),
                ('entity_type', models.CharField(blank=True, default='', help_text='e.g., course, institute', max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.URLField(blank=True, default='')),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
