# Generated by Django 5.1.15 on 2026-05-22 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['company_name'], name='placements_company_fe8934_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['institute', 'placed_date'], name='placements_institu_0f575e_idx'),
        ),
    ]
