# Generated by Django 5.1.15 on 2026-05-22 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon class name or emoji', max_length=50)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'db_table': 'course_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, default='', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='courses/banners/')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_weeks', models.PositiveIntegerField(help_text='Duration in weeks')),
                ('total_hours', models.PositiveIntegerField(default=0, help_text='Total learning hours')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], db_index=True, default='beginner', max_length=20)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], db_index=True, default='online', max_length=20)),
                ('tools_covered', models.JSONField(blank=True, default=list, help_text='List of tools/technologies covered')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='Course highlights')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='Course prerequisites')),
                ('learning_outcomes', models.JSONField(blank=True, default=list, help_text='What students will learn')),
                ('placement_support', models.BooleanField(db_index=True, default=False)),
                ('certification', models.BooleanField(default=True)),
                ('placement_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Placement rate percentage', max_digits=5, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutes.institute')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['-is_featured', '-avg_rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Duration in hours')),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of topic strings')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Syllabus Module',
                'verbose_name_plural': 'Syllabus Modules',
                'db_table': 'syllabus_modules',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['institute', 'is_active'], name='courses_institu_8c98ba_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_active'], name='courses_categor_fe249d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['difficulty', 'mode'], name='courses_difficu_ed84f4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['fees'], name='courses_fees_613075_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured', 'is_trending'], name='courses_is_feat_0c9ddd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syllabusmodule',
            unique_together={('course', 'sort_order')},
        ),
    ]
