# Generated by Django 5.1.15 on 2026-05-22 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course', 'is_approved'], name='reviews_course__f254ac_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['institute', 'is_approved'], name='reviews_institu_8c0fe1_idx'),
        ),
    ]
