# Generated by Django 5.1.15 on 2026-05-22 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['student', 'status'], name='admissions_student_315eca_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['course', 'status'], name='admissions_course__5f785e_idx'),
        ),
    ]
