# Generated by Django 5.1.15 on 2026-05-22 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('page_type', models.CharField(default='landing', help_text='e.g., landing, blog, category', max_length=50)),
            ],
            options={
                'db_table': 'seo_pages',
                'ordering': ['-updated_at'],
            },
        ),
    ]
