# Generated by Django 5.1.15 on 2026-05-22 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('enrolled', 'Enrolled'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('google', 'Google Search'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('direct', 'Direct'), ('advertisement', 'Advertisement'), ('other', 'Other')], db_index=True, default='website', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes by counsellor/admin')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional tracking data')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'db_table': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'enquiry_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
